name: Scala CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        scala-version: [2.12.15]
        java-version: [11]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java-version }}
        cache: 'sbt'
        
    - name: Install SBT
      run: |
        echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | sudo tee /etc/apt/sources.list.d/sbt.list
        echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | sudo tee /etc/apt/sources.list.d/sbt_old.list
        curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | sudo apt-key add
        sudo apt-get update
        sudo apt-get install -y sbt
        
    - name: Cache SBT
      uses: actions/cache@v4
      with:
        path: |
          ~/.sbt
          ~/.ivy2/cache
          ~/.coursier/cache
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt', '**/project/**.scala', '**/project/**.sbt') }}
        restore-keys: |
          ${{ runner.os }}-sbt-
        
    - name: Check code formatting
      run: sbt scalafmtCheckAll
      
    - name: Compile
      run: sbt compile
      
    - name: Compile tests
      run: sbt Test/compile
      
    - name: Run tests
      run: sbt test
      
    - name: Generate coverage report
      run: sbt coverage test coverageReport
      
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        files: ./target/scala-2.12/scoverage-report/scoverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
        
    - name: Package
      run: sbt package
      
    - name: Assembly
      run: sbt assembly
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: scala-spark-pipeline-${{ matrix.scala-version }}
        path: target/scala-2.12/*.jar
        retention-days: 30

  code-quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 11
        cache: 'sbt'
        
    - name: Install SBT
      run: |
        echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | sudo tee /etc/apt/sources.list.d/sbt.list
        echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | sudo tee /etc/apt/sources.list.d/sbt_old.list
        curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | sudo apt-key add
        sudo apt-get update
        sudo apt-get install -y sbt
        
    - name: Check for security vulnerabilities
      run: |
        echo "Running security checks..."
        # Add security scanning tools here if needed
        
    - name: Generate dependency tree
      run: sbt dependencyTree
      
    - name: Check for outdated dependencies
      run: sbt dependencyUpdates
